config/routes.rb
Rails.application.routes.draw do

  root 'routes#root'

  resources :users, only: [:show, :index]
  resource :sessions, only: [:new, :create, :destroy]
  resources :registrations

  resources :menu_items
  resources :items
  resources :sales, only: [:show, :destroy]
  resources :sale_menu_items, only: [:show, :destroy]
  resources :shifts

  resources :manager_pages,only: [] do
    collection do
      get "user_list"
      get "menu_item_list"
      get "payment_list"
      get "sale_list"
      get "sale_menu_item_list"
      get "shift_list"
      get "report_list"
      get "accounting"
      get "stat_sale"
      get "stat_attendance"
    end
  end

  resources :customer_pages,only: [] do
    collection do
      get  "customer_ordering"
      post "create_sale"
      post "report_sale"
    end
  end

  resources :waiter_pages,only: [] do
    collection do
      get "sale_list"
      get "go_for_payment"
      get "verify_payment"
      get "go_deliver"
      get "done_deliver"
      get "delivered_sales"
      post "redo"
    end
    member do
      get "sale_details"
    end
  end

  resources :chief_pages,only: [] do
    collection do
      get "cooking_list"
      get "start_cooking"
      get "done_cooking"
    end
  end

  resources :bartender_pages,only: [] do
    collection do
      get "cooking_list"
      get "start_cooking"
      get "done_cooking"
    end
  end

  resources :cashier_pages,only: [] do
    member do
      get "sale_details"
    end
    collection do
      get "sale_list"
      get "save_sale"
      get "saved_sales"
      get "not_saved_sales"
    end
  end

end

app/controllers/manager_pages_controller.rb
class ManagerPagesController < ApplicationController
  before_action :filter_role
  layout "manager_layout"

  def user_list
    @mg_page = "staff"
    @users = Ckfapi::API::User.index(current_token)['users'] rescue []
  end

  def menu_item_list
    @mg_page = "menu_item"
    @menu_items = Ckfapi::API::MenuItem.index(current_token, detail: true)['menu_items'] rescue []
    @items = Ckfapi::API::Item.index(current_token, detail: true)['items'] rescue []
    @categories = Ckfapi::API::Category.index(current_token)['categories'] rescue []
  end

  def payment_list
    @mg_page = "payment"
    @menu_items = Ckfapi::API::Payment.index(current_token)['payments'] rescue []
  end

  def sale_list
    @mg_page = "sale"
    @sale_menu_items = Ckfapi::API::SaleMenuItem.index(current_token, detail: true)['sale_menu_items'] rescue []
    @sales = Ckfapi::API::Sale.index(current_token, { detail: true })['sales'] rescue []
    respond_to do |format|
      format.html
    end
  end

  def sale_menu_item_list
    @mg_page = "sale"
    @sale_menu_items = Ckfapi::API::SaleMenuItem.index(current_token, detail: true)['sale_menu_items'] rescue []
    respond_to do |format|
      format.js
    end
  end

  def shift_list
    @mg_page = "shift"
    @shifts = Ckfapi::API::Shift.index(current_token, detail: true)['shifts'] rescue []
  end

  def report_list
    @mg_page = "report"
    @reports = Ckfapi::API::Report.index(current_token, detail: true)['reports'] rescue []
  end

  def accounting
    @mg_page = "accounting"
    @shifts = Ckfapi::API::Shift.index(current_token)['shifts'] rescue []
  end

  def stat_sale
    from = Time.parse(params[:datetime][:from])
    to = Time.parse(params[:datetime][:to])
    @sales = Ckfapi::API::Shift.stat(current_token, params[:shift_id], "sale", {
      from: from,
      to: to
    })['stats'] if (!from.blank? && !to.blank?)

    # get sales by menu item
    sales_by_menu_item = @sales['sales'].values.sum.map { |e|
      {
        'id' => e['menu_item_details']['id'],
        'name' => e['menu_item_details']['name'],
        'category' => e['menu_item_details']['category']['name'],
        'klass' => e['menu_item_details']['klass'],
        'mtype' => e['menu_item_details']['mtype'],
        'quantity' => e['quantity'].to_f,
        'total_price' => e['quantity'].to_f*e['menu_item_details']['unit_price'].to_f
      }
    } if @sales
    @sales_by_menu_item = []
    sales_by_menu_item.each do |s|
      if !(el = @sales_by_menu_item.select { |e| e['id'] == s['id'] }[0]).blank?
        el['quantity'] += s['quantity']
        el['total_price'] += s['total_price']
      else
        @sales_by_menu_item << s
      end
    end

    respond_to do |format|
      format.js
    end
  end

  def stat_attendance
    from = Time.parse(params[:datetime][:from])
    to = Time.parse(params[:datetime][:to])
    @attendances = Ckfapi::API::Shift.stat(current_token, params[:shift_id], "attendance", {
      from: from,
      to: to
    })['stats'] if (!from.blank? && !to.blank?)
    respond_to do |format|
      format.js
    end

  end

  private

  def filter_role
    case action_name
    when 'menu_item_list'
      return true if ["Manager", "Chef", "Bartender"].include?(current_user['current_role'])
    else
      return true if ["Manager"].include? current_user['current_role']
    end
    redirect_to get_root_path(current_user)
  end

end

app/views/manager_pages/_menu_item_manage.html.erb
:

app/views/manager_pages/_report_row.html.erb
<tr id="report-<%= report['id'] %>">
<td><%= report['id'] %></td>
<td><%= report['title'] %></td>
<td><%= report['description'] %></td>
<td>
  <% begin %>
    <%= link_to report['user']['email'], user_path(report['user_id']), remote: true %>
    <br />
    <%= report['user']['first_name'] %> <%= report['user']['last_name'] %>
  <% rescue %>
    N/A
  <% end %>
</td>
<td>
  <% begin %>
    <%= link_to report['reported_user']['email'], reported_user_path(report['reported_user_id']), remote: true %>
    <br />
    <%= report['reported_user']['first_name'] %> <%= report['reported_user']['last_name'] %>
  <% rescue %>
    N/A
  <% end %>
</td>
<td><%= report['model'] %></td>
<td><%= report['model_id'] %></td>
<td><%= report['model_dump'] %></td>
<td><%= Time.parse(report['created_at']).in_time_zone(7) %></td>
</tr>

app/views/manager_pages/_sale_by_menu_item_row.html.erb
<tr>
  <td><%= menu_item['name'] %></td>
  <td><%= menu_item['category'] %></td>
  <td><%= menu_item['klass'] %></td>
  <td><%= menu_item['mtype'] %></td>
  <td><%= menu_item['quantity'] %></td>
  <td><%= menu_item['total_price'] %></td>
</tr>

app/views/manager_pages/_sale_menu_item_row.html.erb
<% case sale_menu_item['menu_item_details']['klass'] %>
<% when 'food' %>
<tr id="sale-menu-item-<%= sale_menu_item['id'] %>">
<% when 'drink' %>
<tr id="sale-menu-item-<%= sale_menu_item['id'] %>" class="info">
<% when 'service' %>
<tr id="sale-menu-item-<%= sale_menu_item['id'] %>" class="warning">
<% else %>
<tr id="sale-menu-item-<%= sale_menu_item['id'] %>" >
<% end %>
<td><%= sale_menu_item['id'] %></td>
<td><%= link_to 'Remove', sale_menu_item_path(sale_menu_item['id']), data: {:confirm => 'Are you sure?'}, :method => :delete, remote: true %></td>
<td>
  <%= link_to sale_menu_item['sale']['invoice_number'], 'javascript:;', onclick: "showSale(#{sale_menu_item['sale']['id']})" %>
</td>
<td><%= sale_menu_item['menu_item_details']['name'] %></td>
<td><%= sale_menu_item['menu_item_details']['category']['name'] %></td>
<td><%= sale_menu_item['menu_item_details']['klass'] %></td>
<td><%= sale_menu_item['menu_item_details']['mtype'] %></td>
<td><%= sale_menu_item['quantity'] %></td>
<td><%= sale_menu_item['quantity'].to_f*sale_menu_item['menu_item_details']['unit_price'].to_f %></td>
<td><%= render_state(sale_menu_item['state']) %></td>
<td>
  <%= link_to sale_menu_item['customer']['email'], user_path(sale_menu_item['sale']['customer_id']), remote: true %>
  <br />
  <%= sale_menu_item['customer']['first_name'] %> <%= sale_menu_item['customer']['last_name'] %>
</td>
<td>
  <% begin %>
    <%= link_to sale_menu_item['pender']['email'], user_path(sale_menu_item['pender_id']), remote: true %>
    <br />
    <%= sale_menu_item['pender']['first_name'] %> <%= sale_menu_item['pender']['last_name'] %>
  <% rescue %>
    N/A
  <% end %>
</td>
<td><%= Time.parse(sale_menu_item['sale']['pending_at']).in_time_zone(7) if sale_menu_item['sale']['pending_at'] %></td>
<td>
  <% begin %>
    <%= link_to sale_menu_item['processor']['email'], user_path(sale_menu_item['processor_id']), remote: true %>
    <br />
    <%= sale_menu_item['processor']['first_name'] %> <%= sale_menu_item['processor']['last_name'] %>
  <% rescue %>
    N/A
  <% end %>
</td>
<td><%= Time.parse(sale_menu_item['sale']['processing_at']).in_time_zone(7) if sale_menu_item['sale']['processing_at'] %></td>
<td>
  <% begin %>
    <%= link_to sale_menu_item['maker']['email'], user_path(sale_menu_item['maker_id']), remote: true %>
    <br />
    <%= sale_menu_item['maker']['first_name'] %> <%= sale_menu_item['maker']['last_name'] %>
  <% rescue %>
    N/A
  <% end %>
</td>
<td><%= Time.parse(sale_menu_item['cooking_at']).in_time_zone(7) if sale_menu_item['cooking_at'] %></td>
<td><%= Time.parse(sale_menu_item['done_at']).in_time_zone(7) if sale_menu_item['done_at'] %></td>
<td>
  <% begin %>
    <%= link_to sale_menu_item['deliverer']['email'], user_path(sale_menu_item['deliverer_id']), remote: true %>
    <br />
    <%= sale_menu_item['deliverer']['first_name'] %> <%= sale_menu_item['deliverer']['last_name'] %>
  <% rescue %>
    N/A
  <% end %>
</td>
<td><%= Time.parse(sale_menu_item['delivering_at']).in_time_zone(7) if sale_menu_item['delivering_at'] %></td>
<td><%= Time.parse(sale_menu_item['delivered_at']).in_time_zone(7) if sale_menu_item['delivered_at'] %></td>
<% if false %>
<td>
  <% begin %>
    <%= link_to sale_menu_item['saver']['email'], user_path(sale_menu_item['saver_id']), remote: true %>
    <br />
    <%= sale_menu_item['saver']['first_name'] %> <%= sale_menu_item['saver']['last_name'] %>
  <% rescue %>
    N/A
  <% end %>
</td>
<td><%= Time.parse(sale_menu_item['saved_at']).in_time_zone(7) if sale_menu_item['saved_at'] %></td>
<% end %>
</tr>

app/views/manager_pages/_sale_row.html.erb
<tr>
<td><%= sale['id'] %></td>
<td>
  <%= link_to "View", 'javascript:;', onclick: "showSale(#{sale['id']})" %>
</td>
<td><%= sale['invoice_number'] %></td>
<td><%= render_state(sale['state']).html_safe %></td>
<td>
  <% begin %>
    <%= link_to sale['customer']['email'], user_path(sale['customer_id']), remote: true %>
    <br />
    <%= sale['customer']['first_name'] %> <%= sale['customer']['last_name'] %>
  <% rescue %>
    N/A
  <% end %>
</td>
<td>
  <% begin %>
    <%= link_to sale['pender']['email'], user_path(sale['pender_id']), remote: true %>
    <br />
    <%= sale['pender']['first_name'] %> <%= sale['pender']['last_name'] %>
  <% rescue %>
    N/A
  <% end %>
</td>
<td><%= Time.parse(sale['pending_at']).in_time_zone(7) if sale['pending_at'] %></td>
<td>
  <% begin %>
    <%= link_to sale['processor']['email'], user_path(sale['processor_id']), remote: true %>
    <br />
    <%= sale['processor']['first_name'] %> <%= sale['processor']['last_name'] %>
  <% rescue %>
    N/A
  <% end %>
</td>
<td><%= Time.parse(sale['processing_at']).in_time_zone(7) if sale['processing_at'] %></td>
<td>
  <% begin %>
    <%= link_to sale['saver']['email'], user_path(sale['saver_id']), remote: true %>
    <br />
    <%= sale['saver']['first_name'] %> <%= sale['saver']['last_name'] %>
  <% rescue %>
    N/A
  <% end %>
</td>
<td><%= Time.parse(sale['saved_at']).in_time_zone(7) if sale['saved_at'] %></td>
<td><%= Time.parse(sale['updated_at']).in_time_zone(7) %></td>
<td><%= Time.parse(sale['created_at']).in_time_zone(7) %></td>
</tr>

app/views/manager_pages/_user_row.html.erb
<tr id="user-<%= user['id'] %>">
<td><%= user['id'] %></td>
<td>
  <%= link_to "Edit", edit_registration_path(user['id']), remote: true %>
  <%#= link_to 'Remove', registration_path(user['id']), :confirm => 'Are you sure?', :method => :delete, remote: true %>
  <%= link_to 'Remove', registration_path(user['id']), data: {:confirm => 'Are you sure?'}, :method => :delete, remote: true %>
</td>
<td><%= user['first_name'] %></td>
<td><%= user['last_name'] %></td>
<td><%= user['email'] %></td>
<td><%= user['gender'] %></td>
<td><%= user['role'] %></td>
<td><%= user['current_role'] %></td>
<td><%= user['phone_number']%></td>
<td><%= user['address'] %></td>
<td><%= user['city'] %></td>
<td><%= user['state'] %></td>
<td><%= user['zip'] %></td>
<td><%= user['country'] %></td>
</tr>

app/views/manager_pages/menu_item_list.html.erb
<div class="content">
  <h1> Quản lý món ăn  </h1>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#menu-item-list" aria-controls="menu-item-list" role="tab" data-toggle="tab">MenuItems</a></li>
    <li role="presentation"><a href="#item-list" aria-controls="item-list" role="tab" data-toggle="tab">Items</a></li>
    <li role="presentation"><a href="#new-menu-item" aria-controls="new-menu-item" role="tab" data-toggle="tab">Create MenuItem</a></li>
    <li role="presentation"><a href="#new-item" aria-controls="new-item" role="tab" data-toggle="tab">Create Item</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="menu-item-list">
      <br />
      <div class="menu-items-index">
        <table id="menu-items-table" class="display table table-bordered">
          <thead>
            <th>Id</th>
            <th>Action</th>
            <th>Name</th>
            <!-- <th>Description</th> -->
            <th>Menu Type</th>
            <th>State</th>
            <th>Unit Price</th>
            <th>Unit</th>
            <th>Category</th>
            <th>Image</th>
            <th>Updated At</th>
            <th>Created At</th>
          </thead>
          <tbody>
            <% if @menu_items %>
              <% @menu_items.each do |menu_item| %>
                <tr>
                  <td><%= menu_item['id'] %></td>
                  <td>
                    <%= link_to 'View', menu_item_path(menu_item['id']), remote: true %> <br />
                    <%= link_to 'Edit', edit_menu_item_path(menu_item['id']), remote: true %>
                    <%= link_to 'Remove', menu_item_path(menu_item['id']), data: { confirm: 'Are you sure?' }, :method => :delete, remote: true %>
                  </td>
                  <td><%= menu_item['name'] %></td>
                  <% if false %>
                    <td><%= menu_item['description'] %></td>
                  <% end %>
                  <td><%= menu_item['mtype'] %></td>
                  <td><%= menu_item['state'] %></td>
                  <td><%= menu_item['unit_price'] %></td>
                  <td><%= menu_item['unit'] %></td>
                  <td><%= menu_item['category']['name'] %></td>
                  <td><%= image_tag menu_item['image']['thumb']['url'], style: "width: 200px;" %></td>
                  <td><%= menu_item['updated_at'] %></td>
                  <td><%= menu_item['created_at'] %></td>
                </tr>
              <% end %>
            <% end%>
          </tbody>
          <tfoot>
            <th><input type="text" id="search_id" placeholder="Search ids" class="search_init"></th>
            <th></th>
            <th><input type="text" name="search_name" placeholder="Search names" class="search_init"></th>
            <!-- <th></th> -->
            <th><input type="text" mtype="search_mtype" placeholder="Search mtypes" class="search_init"></th>
            <th><input type="text" state="search_state" placeholder="Search states" class="search_init"></th>
            <th></th>
            <th></th>
            <th><input type="text" category="search_category" placeholder="Search categorys" class="search_init"></th>
            <th></th>
            <th></th>
            <th></th>
          </tfoot>
        </table>
      </div>

    </div>

    <div role="tabpanel" class="tab-pane" id="item-list">
      <br />
      <div class="items-index">
        <table id="items-table" class="display table table-bordered">
          <thead>
            <th>Id</th>
            <th>Action</th>
            <th>Name</th>
            <th>Description</th>
            <th>Unit Price</th>
            <th>Unit</th>
            <th>Updated At</th>
            <th>Created At</th>
          </thead>
          <tbody>
            <% if @items %>
              <% @items.each do |item| %>
                <tr>
                  <td><%= item['id'] %></td>
                  <td>
                    <%= link_to 'Edit', edit_item_path(item['id']), remote: true %>
                    <%#= link_to 'Remove', item_path(item['id']), :confirm => 'Are you sure?', :method => :delete, remote: true %>
                  </td>
                  <td><%= item['name'] %></td>
                  <td><%= item['description'] %></td>
                  <td><%= item['unit_price'] %></td>
                  <td><%= item['unit'] %></td>
                  <td><%= item['updated_at'] %></td>
                  <td><%= item['created_at'] %></td>
                </tr>
              <% end %>
            <% end%>
          </tbody>
          <tfoot>
            <th><input type="text" id="search_id" placeholder="Search ids" class="search_init"></th>
            <th></th>
            <th><input type="text" name="search_name" placeholder="Search names" class="search_init"></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
          </tfoot>
        </table>
      </div>

    </div>

    <div role="tabpanel" class="tab-pane" id="new-menu-item">
      <br />
      <%= form_tag(menu_items_path, method: 'post', remote: true) do %>
        <div class="menu-item-manage">
          <div class="col-xs-4 col-ms-4 col-md-4 col-lg-4" style="border-right: 1px #CCC2C2 solid">
            <h3 class="text-center">1. Chọn thành phần</h3><hr>
            <ul id="items-list-select" class="btn-group" data-toggle="buttons" style="width: 100%">
              <% @items.each do |item| %>
                <li id="item-<%= item['id'] %>-select" class="item-name item-row" style="width: 100%">
                  <label class="btn btn-primary btn-block">
                    <input item-id="<%= item['id'] %>" type="checkbox" autocomplete="off" style="visibility: hidden" onchange="toggleItem(this)"><%= item['name'] %>
                  </label>
                </li>
              <% end %>
            </ul>
          </div>
          <div class="col-xs-4 col-ms-4 col-md-4 col-lg-4">
            <h3 class="text-center">2. Xác đinh lượng</h3><hr>
            <ul id="items-list-form">
              <% @items.each do |item| %>
                <li id="item-<%= item['id'] %>-form" data-price="<%= item['unit_price']%>" class="item-name item-row" style="display: none;">
                  <span class="col-xs-5 col-ms-5 col-md-5 col-lg-5" style="padding: 5px 0;">
                    <%= item['name'] %>(<%= item['unit'] %>)
                    <%= hidden_field_tag 'menu_item[item_menu_items_attributes][][item_id]', item['id'], disabled: 'dissabled' %>
                  </span>
                  <span class="col-xs-4 col-ms-4 col-md-4 col-lg-4">
                    <%= number_field_tag 'menu_item[item_menu_items_attributes][][quantity]', 1, class: "quantity form-control", onchange: "changePrice(this)", disabled: 'disabled' %>
                  </span>
                  <span class="col-xs-3 col-ms-3 col-md-3 col-lg-3 price" style="padding: 5px 0;">
                    <%= item['unit_price'] %>
                  </span>
                </li>
              <% end %>
            </ul>
          </div>
          <div class="col-xs-4 col-ms-4 col-md-4 col-lg-4" style="border-left: 1px #CCC2C2 solid">
            <h3 class="text-center">3. Chi tiết món ăn</h3><hr>
            <%= label_tag 'Image URL' %><br />
            <%= text_field_tag 'menu_item[remote_image_url]', nil, class: 'form-control' %><br />
            <%= label_tag 'Name' %><br />
            <%= text_field_tag 'menu_item[name]', nil, placeholder: "Name", class: 'form-control' %><br />
            <%= label_tag 'Description' %><br />
            <%= text_field_tag 'menu_item[description]', nil, placeholder: "Description", class: 'form-control' %><br />
            <%= label_tag 'Unit' %><br />
            <%= text_field_tag 'menu_item[unit]', nil, placeholder: "Unit", class: 'form-control' %><br />
            <%= label_tag 'Price per Unit' %><br />
            <%= number_field_tag 'menu_item[unit_price]', nil, placeholder: "Price by unit", class: 'form-control' %><br />
            <%= label_tag 'Category' %><br />
            <%= select_tag 'menu_item[category_id]', options_for_select(@categories.collect { |p| [ p['name'] , p['id']] }), class: "form-control" %><br />
            <%= label_tag 'Menu Type' %><br />
            <%= text_field_tag 'menu_item[mtype]', nil, placeholder: "Menu Type (bread, soft drink, ...)", class: 'form-control' %><br />
            <%= label_tag 'Klass (Ex: Food to chef, Drink to Bartender)' %><br />
            <%= select_tag 'menu_item[klass]', options_for_select(['food', 'drink', 'service']), class: "form-control" %><br />

            <%= submit_tag 'Create', class: 'btn btn-default btn-large' %>
          </div>
        </div>
      <% end %>

    </div>

  <div role="tabpanel" class="tab-pane" id="new-item">
      <br />
      <div class="new-item">
        <div class="col-xs-8 col-ms-8 col-md-8 col-lg-8" >
          <h3>Chi tiết Item (Thành phần)</h3><hr>

          <%= form_tag(items_path, method: 'post', remote: true) do %>
            <%= label_tag 'Name' %><br />
            <%= text_field_tag 'item[name]', nil, placeholder: "Name", class: 'form-control' %><br />
            <%= label_tag 'Description' %><br />
            <%= text_field_tag 'item[description]', nil, placeholder: "Description", class: 'form-control' %><br />
            <%= label_tag 'Unit' %><br />
            <%= text_field_tag 'item[unit]', nil, placeholder: "Unit", class: 'form-control' %><br />
            <%= label_tag 'Price per Unit' %><br />
            <%= number_field_tag 'item[unit_price]', nil, placeholder: "Price by unit", class: 'form-control' %><br />

            <%= submit_tag 'Create', class: 'btn btn-default btn-large' %>
          <% end %>
        </div>

      </div>

  </div>

  </div>
</div>


<script>
  $(document).ready(function(){
    var menuItemTable = $('#menu-items-table').dataTable();
    var asInitMenuItemVals = new Array();
    var itemTable = $('#items-table').dataTable();
    var asInitItemVals = new Array();

    $("#menu-items-table tfoot input").keyup( function () {
      /* Filter on the column (the index) of this element */
      menuItemTable.fnFilter( this.value, $("#menu-items-table tfoot th").index($(this).parent()) );
    } );

    /*
     * Support functions to provide a little bit of 'user friendlyness' to the textboxes in
     * the footer
     */
    $("#menu-items-table tfoot input").each( function (i) {
      asInitMenuItemVals[i] = this.value;
    } );

    $("#menu-items-table tfoot input").focus( function () {
      if ( this.className == "search_init" )
      {
        this.className = "";
        this.value = "";
      }
    } );

    $("#menu-items-table tfoot input").blur( function (i) {
      if ( this.value == "" )
      {
        this.className = "search_init";
        this.value = asInitMenuItemVals[$("#menu-items-table tfoot th").index($(this).parent())];
      }
    } );

    /* -------------------------------------- */
    $("#items-table tfoot input").keyup( function () {
      /* Filter on the column (the index) of this element */
      itemTable.fnFilter( this.value, $("#items-table tfoot th").index($(this).parent()) );
    } );

    /*
     * Support functions to provide a little bit of 'user friendlyness' to the textboxes in
     * the footer
     */
    $("#items-table tfoot input").each( function (i) {
      asInitItemVals[i] = this.value;
    } );

    $("#items-table tfoot input").focus( function () {
      if ( this.className == "search_init" )
      {
        this.className = "";
        this.value = "";
      }
    } );

    $("#items-table tfoot input").blur( function (i) {
      if ( this.value == "" )
      {
        this.className = "search_init";
        this.value = asInitItemVals[$("#items-table tfoot th").index($(this).parent())];
      }
    } );
  });
  var changePrice = function(el){
    var unit_price = parseFloat($(el).parent().parent().attr('data-price'));
    var quantity = parseInt($(el).val());
    $(el).parent().siblings('.price').html(parseFloat(unit_price*quantity));
  }

  var toggleItem = function(el){
    var item_id = $(el).attr('item-id');
    if ($(el).is(":checked") == true) {
      $('#item-' + item_id + '-form input').prop('disabled', false);
      $('#item-' + item_id + '-form').show();
    } else {
      $('#item-' + item_id + '-form').hide();
      $('#item-' + item_id + '-form input').prop('disabled', true);
    }
  }
  $('.nav-tabs a').click(function (e) {
    e.preventDefault();
    $(this).tab('show');
  });

</script>

<style>
  .item-row {
    display: table;
    margin-bottom: 2px;
    height: 35px;
  }
  tfoot th input {
    width: 100%;
  }
</style>

app/views/manager_pages/payment_list.html.erb
<div class="content">
  <h1> Đang phát triển </h1>
</div>

app/views/manager_pages/shift_list.html.erb
<div class="content">
  <h1> Shift </h1>
  <%= button_to 'Add Shift', new_shift_path, class: "btn btn-large btn-default", method: :get %>
  <br />
  <table id="shifts-table" class="display table table-bordered">
    <thead>
      <th>Id</th>
      <th>Action</th>
      <th>Start Time</th>
      <th>End Time</th>
    </thead>
    <tbody>
      <% if @shifts %>
        <% @shifts.each do |shift| %>
          <tr>
            <td><%= shift['id'] %></td>
            <td>
              <%= link_to "Edit", edit_shift_path(shift['id']), target: "_blank" %> <br />
              <%= link_to 'Remove', shift_path(shift['id']), :confirm => 'Are you sure?', :method => :delete, remote: true %>
            </td>
            <td><%= Time.parse(shift['start_time']).in_time_zone(7).strftime("%H:%M:%S") %></td>
            <td><%= Time.parse(shift['end_time']).in_time_zone(7).strftime("%H:%M:%S") %></td>
          </tr>
        <% end %>
      <% end%>
    </tbody>
  </table>

  <script>
    $(document).ready(function(){
      $('#shifts-table').DataTable();
    });
  </script>
</div>