config/routes.rb
Rails.application.routes.draw do

  root 'routes#root'

  resources :users, only: [:show, :index]
  resource :sessions, only: [:new, :create, :destroy]
  resources :registrations

  resources :menu_items
  resources :items
  resources :sales, only: [:show, :destroy]
  resources :sale_menu_items, only: [:show, :destroy]
  resources :shifts

  resources :manager_pages,only: [] do
    collection do
      get "user_list"
      get "menu_item_list"
      get "payment_list"
      get "sale_list"
      get "sale_menu_item_list"
      get "shift_list"
      get "report_list"
      get "accounting"
      get "stat_sale"
      get "stat_attendance"
    end
  end

  resources :customer_pages,only: [] do
    collection do
      get  "customer_ordering"
      post "create_sale"
      post "report_sale"
    end
  end

  resources :waiter_pages,only: [] do
    collection do
      get "sale_list"
      get "go_for_payment"
      get "verify_payment"
      get "go_deliver"
      get "done_deliver"
      get "delivered_sales"
      post "redo"
    end
    member do
      get "sale_details"
    end
  end

  resources :chief_pages,only: [] do
    collection do
      get "cooking_list"
      get "start_cooking"
      get "done_cooking"
    end
  end

  resources :bartender_pages,only: [] do
    collection do
      get "cooking_list"
      get "start_cooking"
      get "done_cooking"
    end
  end

  resources :cashier_pages,only: [] do
    member do
      get "sale_details"
    end
    collection do
      get "sale_list"
      get "save_sale"
      get "saved_sales"
      get "not_saved_sales"
    end
  end

end

app/controllers/cashier_pages_controller.rb
class CashierPagesController < ApplicationController
  before_action :filter_role
  layout "cashier_layout"

  def sale_list
  end

  def save_sale
    if !params[:sale_id].blank?
      @sale = update_next_state_sale(current_token,params[:sale_id],"saved")
      @sale['sale']['format_created_at'] = (@sale['sale']['created_at'].to_datetime + 7.hours).strftime("%d/%m/%Y")
      @sale['sale']['order_created_at'] = (@sale['sale']['created_at'].to_datetime + 7.hours).strftime("%Y%m%d%H%M%S")
      @sale['sale']['format_updated_at'] = (@sale['sale']['updated_at'].to_datetime + 7.hours).strftime("<b>%H:%M</b> %d/%m/%Y").html_safe
      @sale['sale']['order_updated_at'] = (@sale['sale']['updated_at'].to_datetime + 7.hours).strftime("%Y%m%d%H%M%S")
      WebsocketRails[:staff].trigger 'next_state_sale_menu_item',@sale
      respond_to do |format|
        format.js
      end
    elsif !params[:sale_menu_id].blank?
      @sale_menu_item =  update_next_state_sale_menu_item(current_token,params[:sale_menu_id],"saved")
      WebsocketRails[:staff].trigger 'next_state_sale_menu_item',@sale_menu_item
      respond_to do |format|
        format.js
      end
    end
    #TODO
  end

  def sale_details
    @sale = Ckfapi::API::Sale.get(current_token, params[:id], detail: true)
    respond_to do |format|
      format.js
    end
  end

  def saved_sales
    shifts = Ckfapi::API::Shift.index(current_token, detail: true)['shifts'] rescue []
    now = Time.now.getutc
    nowp = now.change({year: 1970, month: 1, day: 1})
    current_shift = shifts.select { |p| Time.parse(p['start_time']) < nowp && Time.parse(p['end_time']) > nowp }[0]
    diff = Time.parse(current_shift['start_time']).change({year: now.year, month: now.month, day: now.day}).to_i - Time.parse(current_shift['start_time']).to_i
    start_time = Time.parse(current_shift['start_time']) + diff
    end_time = Time.parse(current_shift['end_time']) + diff
    @sales = Ckfapi::API::Sale.index(current_token, {detail: true, filter: { from: (start_time - 43200), to: end_time } })['sales'] rescue []
    @saved_sales = @sales.select{|m| m['state'] == 'saved'}
  end

  def not_saved_sales
    shifts = Ckfapi::API::Shift.index(current_token, detail: true)['shifts'] rescue []
    now = Time.now.getutc
    nowp = now.change({year: 1970, month: 1, day: 1})
    current_shift = shifts.select { |p| Time.parse(p['start_time']) < nowp && Time.parse(p['end_time']) > nowp }[0]
    diff = Time.parse(current_shift['start_time']).change({year: now.year, month: now.month, day: now.day}).to_i - Time.parse(current_shift['start_time']).to_i
    start_time = Time.parse(current_shift['start_time']) + diff
    end_time = Time.parse(current_shift['end_time']) + diff
    @sales = Ckfapi::API::Sale.index(current_token, {detail: true, filter: { from: (start_time - 43200), to: end_time } })['sales'] rescue []
    @not_saved_sales = @sales.select{|m| m['state'] != 'saved'}
  end

  private

  def filter_role
    return true if ["Manager", "Cashier"].include? current_user['current_role']
    redirect_to get_root_path(current_user)
  end

end

app/helpers/cashier_pages_helper.rb
module CashierPagesHelper

end

app/views/cashier_pages/_modal_sale_details.html.erb
<div class="modal fade" id="modal-sale-details" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-body">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">
          <i class="fa fa-times-circle">
          </i>
          Đóng
        </button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script type="text/javascript">
$('#modal-sale-details').on('shown.bs.modal', function (e) {
  $.ajax({
    type: "GET",
    dataType: "script",
    url: "/cashier_pages/"+sale_details_id+"/sale_details"
  });
})
</script>

app/views/cashier_pages/_not_saved_sale.html.erb
<% notice = sale['service_sale_menu_items_details'].map { |e| e['menu_item_details']['mtype'] }.uniq %>
<tr class='row-sale <%= notice.length > 0 ? "danger" : "" %> <%= "sale-init" if sale['state'] == "init" %> <%=  "sale-delivered" if sale['state'] == "delivered" %>'  sale-id="<%= sale['id'] %>">
  <td>
    <a href="javascript:;" data-toggle="tooltip" data-placement="top" title='<%= notice.join(", ") %>' sale-id="<%= sale['id'] %>" class='show-sale-details' onclick="showSale(<%= sale['id'] %>)" ><%= sale['invoice_number'] %></a>
    <% if sale['state'] == 'delivered' %>
    <a data-remote='true' href='<%= save_sale_cashier_pages_path(sale_id: sale['id']) %>' class='btn-saved-order btn btn-danger btn-xs pull-right'>Lưu lại</a>
    <% end %>
  </td>
  <td>
    <%= sale['customer']['email'] %>
  </td>
  <td>
    <span style='display:none'><%= (sale['created_at'].to_datetime + 7.hours).strftime("%Y%m%d%H%M%S") %></span>
    <%= (sale['created_at'].to_datetime + 7.hours).strftime("%d/%m/%Y <b>%H:%M</b>").html_safe %>
  </td>
  <td>
    <span style='display:none'><%= (sale['updated_at'].to_datetime + 7.hours).strftime("%Y%m%d%H%M%S") %></span>
    <%= (sale['updated_at'].to_datetime + 7.hours).strftime("%d/%m/%Y <b>%H:%M</b>").html_safe %>
  </td>
  <td>
    <b><%= number_with_delimiter(sum(sale)) %></b> đ
  </td>
  <td>
    <center>
      <%= display_state(sale['state']).html_safe %>
    </center>
  </td>
</tr>

<script>
  $(".row-sale[sale-id='<%= sale['id'] %>'] [data-toggle='tooltip']").tooltip();
</script>

app/views/cashier_pages/_order_not_saved.html.erb
<div class="dataTables_wrapper" role="grid">
  <table cellpadding="0" cellspacing="0" border="0" class="table table-hover table-bordered datatables" id="table-order-not-saved">
    <thead>
      <tr>
        <th>
          Mã Hoá Đơn
        </th>
        <th>
          Tên
        </th>
        <th>
          Giờ tạo
        </th>
        <th>
          Giờ cập nhật
        </th>
        <th>
          Tổng Tiền
        </th>
        <th style='width: 15%;'>
          <center>
            Trạng Thái
          </center>
        </th>
      </tr>
    </thead>
    <tbody>
      <tr class="not-saved-loading">
        <td colspan="6">
          <center>
            <i class='fa fa-spin fa-spinner' style="margin-right: 5px"></i> Đang tải dữ liệu
          </center>
        </td>
      </tr>
      <tr class="no-not-saved-orders no-orders" style="display: none">
        <td colspan="6">
          <div class="alert alert-warning">Tạm thời không có order mới.</div>
        </td>
      </tr>
      <script type="text/javascript">
      $.ajax({
        type: "GET",
        dataType: "script",
        url: "<%= not_saved_sales_cashier_pages_path %>"
      });
      </script>
    </tbody>
  </table>
</div>

app/views/cashier_pages/_order_saved.html.erb
<div class="dataTables_wrapper" role="grid">
  <table cellpadding="0" cellspacing="0" border="0" class="table table-hover table-bordered datatables" id="table-order-saved">
    <thead>
      <tr>
        <th>
          Mã Hoá Đơn
        </th>
        <th>
          Tên
        </th>
        <th>
          Giờ tạo
        </th>
        <th>
          Giờ cập nhật
        </th>
        <th>
          Tổng Tiền
        </th>
        <th style='width: 15%;'>
          <center>
            Trạng Thái
          </center>
        </th>
      </tr>
    </thead>
    <tbody>
      <tr class="saved-loading" style="display: none">
        <td colspan="6">
          <center>
            <i class='fa fa-spin fa-spinner' style="margin-right: 5px"></i> Đang tải dữ liệu
          </center>
        </td>
      </tr>
      <tr class="no-saved-orders no-orders">
        <td colspan="6">
          <div class="alert alert-warning">Tạm thời không có order mới.</div>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/cashier_pages/_sale.html.erb
<% notice = sale['service_sale_menu_items_details'].map { |e| e['menu_item_details']['mtype'] }.uniq %>
<tr class='row-sale <%= notice.length > 0 ? "danger" : "" %>'  sale-id="<%= sale['id'] %>">
  <td>
    <a href="javascript:;" data-toggle="tooltip" data-placement="top" title='<%= notice.join(", ") %>' sale-id="<%= sale['id'] %>" class='show-sale-details' onclick="showSale(<%= sale['id'] %>)" ><%= sale['invoice_number'] %></a>
  </td>
  <td>
    <%= sale['customer']['email'] %>
  </td>
  <td>
    <span style='display:none'><%= (sale['created_at'].to_datetime + 7.hours).strftime("%Y%m%d%H%M%S") %></span>
    <%= (sale['created_at'].to_datetime + 7.hours).strftime("%d/%m/%Y <b>%H:%M</b>").html_safe %>
  </td>
  <td>
    <span style='display:none'><%= (sale['updated_at'].to_datetime + 7.hours).strftime("%Y%m%d%H%M%S") %></span>
    <%= (sale['updated_at'].to_datetime + 7.hours).strftime("%d/%m/%Y <b>%H:%M</b>").html_safe %>
  </td>
  <td>
    <b><%= number_with_delimiter(sum(sale)) %></b> đ
  </td>
  <td>
    <center>
      <%= display_state(sale['state']).html_safe %>
    </center>
  </td>
</tr>

<script>
  $(".row-sale[sale-id='<%= sale['id'] %>'] [data-toggle='tooltip']").tooltip();
</script>

app/views/cashier_pages/_sale_details.html.erb
<div class="row">
  <div class="col-lg-12">
    <center>
      <h3>
        CHI TIẾT HOÁ ĐƠN
        <br>
        <p style='color: #777; font-size: 20px; margin-top: 10px'><%= @sale['sale']['invoice_number'] %></p>
      </h3>
    </center>
  </div>
</div>
<br>
<div class="row">
  <div class="col-lg-4 col-md-4 col-sm-6">
    <p>
      <b>Tên máy:</b> <%= sale['customer']['email'] %>
    </p>
  </div>
  <div class="col-lg-4 col-md-4 col-sm-6">
    <p>
      <b>Tạo lúc:</b> <%= (sale['created_at'].to_datetime + 7.hours).strftime("%H:%M %d/%m/%Y") %>
    </p>
  </div>
  <div class="col-lg-4 col-md-4 col-sm-6">
    <p>
      <b>Trạng thái:</b> <%= render_state(sale['state']).html_safe %>
    </p>
  </div>
</div>
<br>
<div class="row">
  <% unless sale['processor'].nil? %>
  <div class="col-lg-4 col-md-4 col-sm-6">
    <p>
      <b>Nhân viên thu:</b> <%= "#{sale['processor']['last_name']} #{sale['processor']['first_name']}" %>
    </p>
    <p>
      <b>Thu lúc:</b> <%= ((sale['processing_at'].to_datetime rescue DateTime.now) + 7.hours).strftime("%H:%M %d/%m/%Y") %>
    </p>
  </div>
  <% end %>
  <% unless sale['done_at'].nil? %>
  <div class="col-lg-4 col-md-4 col-sm-6">
    <p>
      <b>Xong lúc:</b> <%= ((sale['done_at'].to_datetime rescue DateTime.now) + 7.hours).strftime("%H:%M %d/%m/%Y") %>
    </p>
  </div>
  <% end %>
  <% unless sale['delivered_at'].nil? %>
  <div class="col-lg-4 col-md-4 col-sm-6">
    <p>
      <b>Giao lúc:</b> <%= ((sale['delivered_at'].to_datetime rescue DateTime.now) + 7.hours).strftime("%H:%M %d/%m/%Y") %>
    </p>
  </div>
  <% end %>
</div>
<br>
<div class="row">
  <div class="col-lg-12">
    <table class='table table-bordered'>
      <thead style="background-color: #428bca; color: #fff; border: 1px solid #428bca;">
        <tr>
          <th>Món</th>
          <th>Trạng Thái</th>
          <th>Số lượng</th>
          <th>Đơn giá</th>
        </tr>
      </thead>
      <tbody>
        <!-- FOOD -->
        <% sale['food_sale_menu_items_details'].each do |item| %>
        <tr>
          <td style="width: 30%">
            <%= item['menu_item_details']['name'] %>
          </td>
	  <td style="width: 30%">
            <%= item['state'] %>
          </td>
          <td style="width: 20%">
            <%= item['quantity'].to_i %>
          </td>
          <td style="width: 20%">
            <%= number_with_delimiter(item['menu_item_details']['unit_price'].to_i) %> đ
          </td>
        </tr>
        <% end %>
        <!-- DRINK -->
        <% sale['drink_sale_menu_items_details'].each do |item| %>
        <tr>
          <td style="width: 30%">
            <%= item['menu_item_details']['name'] %>
          </td>
	  <td style="width: 30%">
            <%= item['state'] %>
          </td>
          <td style="width: 20%">
            <%= item['quantity'].to_i %>
          </td>
          <td style="width: 20%">
            <%= number_with_delimiter(item['menu_item_details']['unit_price'].to_i) %> đ
          </td>
        </tr>
        <% end %>
        <!-- SERVICE -->
        <% sale['service_sale_menu_items_details'].each do |item| %>
        <tr class="row-nocook">
          <td style="width: 30%">
            <%= item['menu_item_details']['name'] %>
          </td>
	  <td style="width: 30%">
            <%= item['state'] %>
          </td>
          <td style="width: 20%">
            <%= item['quantity'].to_i %>
          </td>
          <td style="width: 20%">
            <%= number_with_delimiter(item['menu_item_details']['unit_price'].to_i) %> đ
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>
<div class="row">
  <div class="col-lg-12">
    <div class="pull-right">
      <h4>Tổng: <b><%= number_with_delimiter(sum(sale)) %> đ</b></h4>
    </div>
  </div>
</div>

app/views/cashier_pages/not_saved_sales.js.erb
<% if @not_saved_sales.count > 0 %>
$(".no-not-saved-orders").fadeOut(100)
$('#table-order-not-saved tbody').html("");
<% @not_saved_sales.each do |sale| %>
  $('#table-order-not-saved tbody').append("<%=j render partial: 'not_saved_sale', locals: { sale: sale} %>");
<% end %>
<% else %>
$(".no-not-saved-orders").fadeIn(100)
$('#table-order-not-saved tbody').html("");
<% end %>

var not_saved_table = $("#table-order-not-saved").dataTable({
  "sDom": "<'row'<'col-lg-6'l><'col-lg-6'f>r>t<'row'<'col-lg-2'i><'col-lg-10'p>>",
  "sPaginationType": "full_numbers",
  "order": [[ 3, "desc" ]],
  "oLanguage": {
    "sLengthMenu": "<%= t('datatable.length_menu') %>",
    "sSearch": "",
    "sInfo": "<%= t('datatable.info') %>",
    "oPaginate": {
      "sNext": "<%= t('datatable.paginate_next') %>",
      "sPrevious": "<%= t('datatable.paginate_previous') %>",
      "sFirst": "<%= t('datatable.paginate_first') %>",
      "sLast": "<%= t('datatable.paginate_last') %>",
    }
  },
  "aaSorting": [],
  "aoColumnDefs" : [ {
    'bSortable' : false,
    'aTargets' : []
  } ]
});
$('.dataTables_filter input').addClass('form-control').attr('placeholder',"<%= t('datatable.search') %>");
$('.dataTables_length select').addClass('form-control');

$(".btn-saved-order").click(function(){
  $(this).parents('.row-sale').remove()
})

app/views/cashier_pages/sale_details.js.erb
$("#modal-sale-details .modal-body").html("<%=j render 'sale_details', sale: @sale['sale'] %>")

app/views/cashier_pages/sale_list.html.erb
<script type="text/javascript">
var staff_channel = dispatcher.subscribe('staff');
var stack_context = {"dir1": "down", "dir2": "left", "push": "bottom", "spacing1": 5, "spacing2": 5}
</script>
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <div class="cashier-pages">
        <div class="row tabs-row">
          <div class="col-sm-6 col-lg-6 col-md-6 col-xs-6 no-padding">
            <div class="tab-list active" aria-control="tab-order-saved">
              DANH SÁCH ORDER
            </div>
          </div>
          <div class="col-sm-6 col-lg-6 col-md-6 col-xs-6 no-padding">
            <div class="tab-list" aria-control="tab-order-done">
              ORDER ĐÃ LƯU
            </div>
          </div>
        </div>
        <div class="row tabs-content">
          <div class="col-sm-12">
            <div style='padding: 15px'>
              <div class="tab-content" id="tab-order-saved">
                <%= render 'order_not_saved' %>
              </div>
              <div class="tab-content" id="tab-order-done">
                <%= render 'order_saved' %>
              </div>
            </div>
          </div>
          <br>
          <center>
            <a data-method="DELETE" href="/sessions">Đăng xuất</a>
          </center>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
$(document).ready(function () {
  if($("#table-order-not-saved .row-sale.sale-init").length + $("#table-order-not-saved .row-sale.sale-delivered").length > 0){
    $(".notify-order-all").fadeIn(0)
  }
  else{
    $(".notify-order-all").fadeOut(0)
  }
  set_notifications_number()
});

setInterval(function(){
  if(window.confirm("Bạn có muốn tải lại trang này không? (Tải lại sẽ giúp bạn cập nhật được order mới)")){
    if (typeof not_saved_table != 'undefined'){
      not_saved_table.fnDestroy()
    }
    $("#table-order-not-saved tbody").html('<tr><td colspan="6"><center><i class="fa fa-spin fa-spinner" style="margin-right: 5px"></i> Đang tải dữ liệu</center></td></tr>')
    $.ajax({
      type: "GET",
      dataType: "script",
      url: "<%= not_saved_sales_cashier_pages_path %>"
    });
  }
}, 1000 * 3600 * 5);


$(".tab-list").click(function(){
  $(".tab-list").removeClass("active")
  $(this).addClass("active")
  tab_id = $(this).attr("aria-control")
  $(".tab-content").fadeOut(0)
  $("#"+tab_id).fadeIn(300)
  if(tab_id == "tab-order-done"){
    if(window.confirm("Bạn có muốn tải lại trang này không? (Tải lại sẽ giúp bạn cập nhật được order mới lưu)")){
      if (typeof saved_table != 'undefined'){
        saved_table.fnDestroy()
      }
      $("#table-order-saved tbody").html('<tr><td colspan="6"><center><i class="fa fa-spin fa-spinner" style="margin-right: 5px"></i> Đang tải dữ liệu</center></td></tr>')
      $.ajax({
        type: "GET",
        dataType: "script",
        url: "<%= saved_sales_cashier_pages_path %>"
      });
    }
  }
})

function render_label_state(state){
  switch(state) {
    case "init":
    return "<center><label class='label label-default'>Order mới</label></center>"
    break;
    case "pending":
    return "<center><label class='label label-info'>Đang lấy tiền</label></center>"
    break;
    case "processing":
    return "<center><label class='label label-primary'>Đã lấy tiền</label</center>"
    break;
    case "cooking":
    return "<center><label class='label label-warning'>Đang làm</label></center>"
    break;
    case "done":
    return "<center><label class='label label-danger'>Làm xong</label></center>"
    break;
    case "delivering":
    return "<center><label class='label label-success'>Đang giao</label></center>"
    break;
    case "delivered":
    return "<center><label class='label label-green'>Đã giao</label></center>"
    break;
    default:
    return "<center><label class='label label-inverse'>Đã lưu</label></center>"
  }
}

function set_notifications_number(){
  notifications_number = $(".row-sale.sale-init").length + $(".row-sale.sale-delivered").length
  if(notifications_number > 0)
  {
    $(".notify-order-all").fadeIn(0)
    $(".notify-order-all").text(notifications_number)
  }
  else{
    $(".notify-order-all").fadeOut(0)
  }
}

var showSale = function(id){
    $('.launch-modal').html("<%=j render 'sales/modal_sale_details' %>");
    $('#modal-sale-details').attr("sale-id", id);
    $("#modal-sale-details").modal({
      keyboard: true,
      backdrop: 'static'
    });
  }
</script>

app/views/cashier_pages/saved_sales.js.erb
<% if @saved_sales.count > 0 %>
$(".no-saved-orders").fadeOut(100)
$('#table-order-saved tbody').html("");
<% @saved_sales.each do |sale| %>
  $('#table-order-saved tbody').append("<%=j render partial: 'sale', locals: { sale: sale} %>");
<% end %>
<% else %>
$(".no-saved-orders").fadeIn(100)
$('#table-order-saved tbody').html("");
<% end %>

var saved_table = $("#table-order-saved").dataTable({
  "sDom": "<'row'<'col-lg-6'l><'col-lg-6'f>r>t<'row'<'col-lg-2'i><'col-lg-10'p>>",
  "sPaginationType": "full_numbers",
  "order": [[ 3, "desc" ]],
  "oLanguage": {
    "sLengthMenu": "<%= t('datatable.length_menu') %>",
    "sSearch": "",
    "sInfo": "<%= t('datatable.info') %>",
    "oPaginate": {
      "sNext": "<%= t('datatable.paginate_next') %>",
      "sPrevious": "<%= t('datatable.paginate_previous') %>",
      "sFirst": "<%= t('datatable.paginate_first') %>",
      "sLast": "<%= t('datatable.paginate_last') %>",
    }
  },
  "aaSorting": [],
  "aoColumnDefs" : [ {
    'bSortable' : false,
    'aTargets' : []
  } ]
});
$('.dataTables_filter input').addClass('form-control').attr('placeholder',"<%= t('datatable.search') %>");
$('.dataTables_length select').addClass('form-control');