config/routes.rb
Rails.application.routes.draw do

  root 'routes#root'

  resources :users, only: [:show, :index]
  resource :sessions, only: [:new, :create, :destroy]
  resources :registrations

  resources :menu_items
  resources :items
  resources :sales, only: [:show, :destroy]
  resources :sale_menu_items, only: [:show, :destroy]
  resources :shifts

  resources :manager_pages,only: [] do
    collection do
      get "user_list"
      get "menu_item_list"
      get "payment_list"
      get "sale_list"
      get "sale_menu_item_list"
      get "shift_list"
      get "report_list"
      get "accounting"
      get "stat_sale"
      get "stat_attendance"
    end
  end

  resources :customer_pages,only: [] do
    collection do
      get  "customer_ordering"
      post "create_sale"
      post "report_sale"
    end
  end

  resources :waiter_pages,only: [] do
    collection do
      get "sale_list"
      get "go_for_payment"
      get "verify_payment"
      get "go_deliver"
      get "done_deliver"
      get "delivered_sales"
      post "redo"
    end
    member do
      get "sale_details"
    end
  end

  resources :chief_pages,only: [] do
    collection do
      get "cooking_list"
      get "start_cooking"
      get "done_cooking"
    end
  end

  resources :bartender_pages,only: [] do
    collection do
      get "cooking_list"
      get "start_cooking"
      get "done_cooking"
    end
  end

  resources :cashier_pages,only: [] do
    member do
      get "sale_details"
    end
    collection do
      get "sale_list"
      get "save_sale"
      get "saved_sales"
      get "not_saved_sales"
    end
  end

end

app/controllers/waiter_pages_controller.rb
class WaiterPagesController < ApplicationController
  before_action :filter_role
  layout "waiter_layout"

  def sale_list
    @sales = Ckfapi::API::Sale.index(current_token, detail: true)['sales'] rescue []
    @sales = @sales.sort{|a, b| a['created_at'].to_datetime <=> b['created_at'].to_datetime}
    @sales_pending = []
    @sales_ready = []
    @sales_delivered = []
    @histories = params[:histories]
    @sales.each do |sale|
      if ["init", "pending"].include?(sale['state'])
        @sales_pending << sale if sale['state'] == "pending" && current_user['id'] == sale['pender_id']
        @sales_pending << sale if sale['state'] == "init"
      elsif ['done', 'processing'].include?(sale['state'])
        @sales_ready << sale if sale['state'] == "processing"
        @sales_ready << sale if sale['state'] == "done"
      else
        @sales_delivered << sale
      end
    end
    respond_to do |format|
      format.html
    end
  end

  def init_sale_list
    #TODOt
  end

  def done_sale_list
    #TODO
  end

  def go_for_payment
    if !params[:sale_id].blank?
      @sale = update_next_state_sale(current_token,params[:sale_id],"pending")
      @sale['sale']['format_created_at'] = (@sale['sale']['created_at'].to_datetime + 7.hours).strftime("%d/%m/%Y")
      @sale['sale']['order_created_at'] = (@sale['sale']['created_at'].to_datetime + 7.hours).strftime("%Y%m%d%H%M%S")
      @sale['sale']['format_updated_at'] = (@sale['sale']['updated_at'].to_datetime + 7.hours).strftime("<b>%H:%M</b> %d/%m/%Y").html_safe
      @sale['sale']['order_updated_at'] = (@sale['sale']['updated_at'].to_datetime + 7.hours).strftime("%Y%m%d%H%M%S")
      WebsocketRails[:staff].trigger 'next_state_sale',@sale
      respond_to do |format|
        format.js
      end
    elsif !params[:sale_menu_id].blank?
      @sale_menu_item =  update_next_state_sale_menu_item(current_token,params[:sale_menu_id],"pending")
      WebsocketRails[:staff].trigger 'next_state_sale_menu_item',@sale_menu_item
      respond_to do |format|
        format.js
      end
    end
    #TODO
  end

  def verify_payment
    if !params[:sale_id].blank?
      @sale = update_next_state_sale(current_token,params[:sale_id],"processing")
      @sale['sale']['format_created_at'] = (@sale['sale']['created_at'].to_datetime + 7.hours).strftime("%d/%m/%Y")
      @sale['sale']['order_created_at'] = (@sale['sale']['created_at'].to_datetime + 7.hours).strftime("%Y%m%d%H%M%S")
      @sale['sale']['format_updated_at'] = (@sale['sale']['updated_at'].to_datetime + 7.hours).strftime("<b>%H:%M</b> %d/%m/%Y").html_safe
      @sale['sale']['order_updated_at'] = (@sale['sale']['updated_at'].to_datetime + 7.hours).strftime("%Y%m%d%H%M%S")
      @sale['sale']['is_food_sale'] = @sale['sale']['food_sale_menu_items_details'].any?{|f| ['cooking', 'processing'].include?(f['state'])}
      @sale['sale']['is_drink_sale'] = @sale['sale']['drink_sale_menu_items_details'].any?{|f| ['cooking', 'processing'].include?(f['state'])}

      @sale['sale']['food_sale_menu_items_details'].each do |item|
        case item['state']
        when "done"
          item['format_done_at'] = "#{(item['done_at'].to_datetime + 7.hours).strftime('<b>%H:%M</b> %d/%m/%Y')}".html_safe
        when "delivering"
          item['format_delivering_at'] = "#{(item['delivering_at'].to_datetime + 7.hours).strftime('<b>%H:%M</b> %d/%m/%Y')}".html_safe
        when "delivered"
          item['format_delivered_at'] = "#{(item['delivered_at'].to_datetime + 7.hours).strftime('<b>%H:%M</b> %d/%m/%Y')}".html_safe
        end
      end

      @sale['sale']['drink_sale_menu_items_details'].each do |item|
        case item['state']
        when "done"
          item['format_done_at'] = "#{(item['done_at'].to_datetime + 7.hours).strftime('<b>%H:%M</b> %d/%m/%Y')}".html_safe
        when "delivering"
          item['format_delivering_at'] = "#{(item['delivering_at'].to_datetime + 7.hours).strftime('<b>%H:%M</b> %d/%m/%Y')}".html_safe
        when "delivered"
          item['format_delivered_at'] = "#{(item['delivered_at'].to_datetime + 7.hours).strftime('<b>%H:%M</b> %d/%m/%Y')}".html_safe
        end
      end

      @sale['sale']['service_sale_menu_items_details'].each do |item|
        case item['state']
        when "done"
          item['format_done_at'] = "#{(item['done_at'].to_datetime + 7.hours).strftime('<b>%H:%M</b> %d/%m/%Y')}".html_safe
        when "delivering"
          item['format_delivering_at'] = "#{(item['delivering_at'].to_datetime + 7.hours).strftime('<b>%H:%M</b> %d/%m/%Y')}".html_safe
        when "delivered"
          item['format_delivered_at'] = "#{(item['delivered_at'].to_datetime + 7.hours).strftime('<b>%H:%M</b> %d/%m/%Y')}".html_safe
        end
      end
      WebsocketRails[:staff].trigger 'next_state_sale',@sale
      respond_to do |format|
        format.js
      end
    elsif !params[:sale_menu_id].blank?
      @sale_menu_item =  update_next_state_sale_menu_item(current_token,params[:sale_menu_id],"processing")
      WebsocketRails[:staff].trigger 'next_state_sale_menu_item',@sale_menu_item
      respond_to do |format|
        format.js
      end
    end
    #TODO
  end

  def go_deliver
    if !params[:sale_id].blank?
      @sale = update_next_state_sale(current_token,params[:sale_id],"delivering")
      @sale['sale']['format_created_at'] = (@sale['sale']['created_at'].to_datetime + 7.hours).strftime("%d/%m/%Y")
      @sale['sale']['order_created_at'] = (@sale['sale']['created_at'].to_datetime + 7.hours).strftime("%Y%m%d%H%M%S")
      @sale['sale']['format_updated_at'] = (@sale['sale']['updated_at'].to_datetime + 7.hours).strftime("<b>%H:%M</b> %d/%m/%Y").html_safe
      @sale['sale']['order_updated_at'] = (@sale['sale']['updated_at'].to_datetime + 7.hours).strftime("%Y%m%d%H%M%S")
      WebsocketRails[:staff].trigger 'next_state_sale',@sale
      respond_to do |format|
        format.js
      end
    elsif !params[:sale_menu_id].blank?
      @sale_menu_item =  update_next_state_sale_menu_item(current_token,params[:sale_menu_id],"delivering")
      @sale_menu_item['sale_menu_item']['format_delivering_at'] = (@sale_menu_item['sale_menu_item']['delivering_at'].to_datetime + 7.hours).strftime("<b>%H:%M</b> %d/%m/%Y")
      WebsocketRails[:staff].trigger 'next_state_sale_menu_item',@sale_menu_item
      respond_to do |format|
        format.js
      end
    end
    #TODO
  end

  def done_deliver
    if !params[:sale_id].blank?
      @sale = update_next_state_sale(current_token,params[:sale_id],"delivered")
      @sale['sale']['format_created_at'] = (@sale['sale']['created_at'].to_datetime + 7.hours).strftime("%d/%m/%Y")
      @sale['sale']['order_created_at'] = (@sale['sale']['created_at'].to_datetime + 7.hours).strftime("%Y%m%d%H%M%S")
      @sale['sale']['format_updated_at'] = (@sale['sale']['updated_at'].to_datetime + 7.hours).strftime("<b>%H:%M</b> %d/%m/%Y").html_safe
      @sale['sale']['order_updated_at'] = (@sale['sale']['updated_at'].to_datetime + 7.hours).strftime("%Y%m%d%H%M%S")
      WebsocketRails[:staff].trigger 'next_state_sale',@sale
      respond_to do |format|
        format.js
      end
    elsif !params[:sale_menu_id].blank?
      @sale_menu_item =  update_next_state_sale_menu_item(current_token,params[:sale_menu_id],"delivered")
      @sale_menu_item['sale_menu_item']['format_delivered_at'] = (@sale_menu_item['sale_menu_item']['delivered_at'].to_datetime + 7.hours).strftime("<b>%H:%M</b> %d/%m/%Y")
      WebsocketRails[:staff].trigger 'next_state_sale_menu_item',@sale_menu_item
      respond_to do |format|
        format.js
      end
    end
    #TODO
  end

  def sale_details
    @sale = Ckfapi::API::Sale.get(current_token, params[:id], detail: true)
    respond_to do |format|
      format.js
    end
  end

  def delivered_sales
    @sales = Ckfapi::API::Sale.index(current_token,detail: true)['sales'] rescue []
    @sales = @sales.sort{|a, b| b['updated_at'].to_datetime <=> a['updated_at'].to_datetime}
    @delivered_sales = @sales.select{|m| m['state'] == 'delivered' || m['state'] == "saved"}
  end

  def redo
    if !params[:sale_id].blank?
      respond_to do |format|
        format.js {

        }
      end
    elsif !params[:sale_menu_id].blank?
      respond_to do |format|
        format.js {
          @sale_menu_item = redo_sale_menu_item(current_token, params[:sale_menu_id], params[:reason])
          @sale_menu_item['sale_menu_item']['sale']['is_food_sale'] = @sale_menu_item['sale_menu_item']['menu_item_details']['klass'] == "food"
          @sale_menu_item['sale_menu_item']['sale']['is_drink_sale'] = @sale_menu_item['sale_menu_item']['menu_item_details']['klass'] == "drink"
          @sale_menu_item['sale_menu_item']['reason'] = params[:reason]
          @sale_menu_item['sale_menu_item']['sale']['format_created_at'] = (@sale_menu_item['sale_menu_item']['sale']['created_at'].to_datetime + 7.hours).strftime("%d/%m/%Y")
          WebsocketRails[:staff].trigger 'next_state_sale_menu_item', @sale_menu_item
        }
      end
    end
  end

  private

  def filter_role
    return true if ["Waiter"].include? current_user['current_role']
    redirect_to get_root_path(current_user)
  end
end

app/helpers/waiter_pages_helper.rb
module WaiterPagesHelper
  def get_class_menu_item(state)
    case state
    when "done"
      "danger"
    when "delivering"
      "warning"
    when "delivered"
      "success"
    end
  end

  def get_item_action_at(item)
    case item['state']
    when 'done'
      "Xong lúc: #{(item['done_at'].to_datetime + 7.hours).strftime('<b>%H:%M</b> %d/%m/%Y')}".html_safe
    when 'delivering'
      "Đi giao lúc: #{(item['delivering_at'].to_datetime + 7.hours).strftime('<b>%H:%M</b> %d/%m/%Y')}".html_safe
    when 'delivered'
      "Giao xong lúc: #{(item['delivered_at'].to_datetime + 7.hours).strftime('<b>%H:%M</b> %d/%m/%Y')}".html_safe
    else
      "Đang chờ"
    end
  end
end

app/views/waiter_pages/_order_histories.html.erb
<table class="table table-bordered table-order-histories table-order">
  <thead>
    <tr>
      <th style="width: 25%">
        <i class='fa fa-desktop' style='font-size: 25px; padding-top: 10px; position: relative'></i>
      </th>
      <th style="width: 75%;">
        Số tiền đã thu
      </th>
    </tr>
  </thead>
  <tbody>
    <tr class="histories-loading" style="display: none">
      <td colspan="2">
        <center>
          <i class="fa fa-spin fa-spinner" style="margin-right: 5px"></i> Đang tải dữ liệu
        </center>
      </td>
    </tr>
    <tr class="no-histories-orders">
      <td colspan="3">
        <div class="alert alert-warning">Tạm thời không có order mới.</div>
      </td>
    </tr>
  </tbody>
</table>

app/views/waiter_pages/_order_pending.html.erb
<table class="table table-bordered table-order-pending table-order">
  <thead>
    <tr>
      <th style="width: 25%">
        <i class='fa fa-desktop' style='font-size: 25px; padding-top: 10px; position: relative'></i>
      </th>
      <th style="width: 75%;">
        Số tiền cần thu
      </th>
    </tr>
  </thead>
  <tbody>
    <% @sales_pending.each do |sale| %>
    <tr data-target="#order-action-dropdown-<%= sale['id'] %>" data-toggle="dropdown" class="order-row <%= 'success' if sale['state'] == 'pending' %>" sale-id='<%= sale['id'] %>' id="sale-<%= sale['id'] %>">
      <td class="order-com">
        <%= sale['customer']['email'] %>
      </td>
      <td class="order-price">
        <div id="order-action-dropdown-<%= sale['id'] %>" class="btn-group order-action pull-right" style="margin-top: 12px">
          <button type="button" data-target="#order-action-dropdown-<%= sale['id'] %>" style="padding-bottom: 2px;" class="btn btn-sm btn-primary dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <i class='fa fa-caret-down' style='font-size: 18px'></i>
          </button>
          <ul class="dropdown-menu">
            <li class='<%= sale['state'] == 'init' ? 'active' : '' %>'>
              <a class='btn-go-to-payment' <%= "data-remote=true" if sale['state'] == 'init' %> href="<%= sale['state'] == 'init' ? go_for_payment_waiter_pages_path(sale_id: sale['id']) : 'javascript:;' %>">Đi thu tiền</a>
            </li>
            <li class='<%= sale['state'] == 'pending' ? 'active' : '' %>'>
              <a class='btn-verify-payment' <%= "data-remote=true" if sale['state'] == 'pending' %> href="<%= sale['state'] == 'pending' ? verify_payment_waiter_pages_path(sale_id: sale['id']) : 'javascript:;' %>">Đã thu tiền</a>
            </li>
            <li role="separator" class="divider"></li>
            <li class='active'><a href="javascript:;" class="btn-order-details" sale-id="<%= sale['id'] %>">Xem chi tiết</a></li>
          </ul>
        </div>
        <div class="total-price" style="">
          <span class='price'>
            <%= number_with_delimiter((sale['food_sale_menu_items_details'].map{|a| a['sum'].to_i}.reduce(:+) || 0 rescue 0) + (sale['drink_sale_menu_items_details'].map{|a| a['sum'].to_i}.reduce(:+) || 0 rescue 0) + (sale['service_sale_menu_items_details'].map{|a| a['sum'].to_i}.reduce(:+) || 0 rescue 0)) %>
          </span>
          <span style='color: #999'>đ</span>
        </div>
        <small class="pull-left order-created-at" style='margin-top: 3px; margin-left: 1px'>
          Gọi lúc: <%= (sale['created_at'].to_datetime + 7.hours).strftime("<b>%H:%M</b> %d/%m/%Y").html_safe %>
        </small>
      </td>
    </tr>
    <% end %>
    <tr class="no-pending-orders no-orders">
      <td colspan="3">
        <div class="alert alert-warning">Tạm thời không có order mới.</div>
      </td>
    </tr>
  </tbody>
</table>

<script type="text/javascript">
$(document).ready(function () {
  if($(".table-order-pending .order-row").length > 0){
    $(".notify-order-pending").fadeIn(0)
    $(".no-pending-orders").fadeOut(0)
  }
  else{
    $(".notify-order-pending").fadeOut(0)
    $(".no-pending-orders").fadeIn(0)
  }
});

$(".table-order-pending").on("click", ".order-row", function(){
  $(".order-row").removeClass("select-now")
  if($(this).hasClass("select-now"))
  {
    $(this).addClass("remove-now")
  }
  else{
    $(this).addClass("select-now")
  }
})

$(".table-order-pending").on("click", ".btn-order-details", function(){
  sale_id = $(this).attr("sale-id")
  $('.launch-modal').html("<%=j render 'waiter_pages/modal_sale_details' %>")
  $('#modal-sale-details').attr("sale-id", sale_id)
  $("#modal-sale-details").modal({
    keyboard: true,
    backdrop: 'static'
  })
})

$(".table-order-pending").on("click", ".active .btn-verify-payment", function(){
  $(this).parents(".order-row").remove()
  set_notifications_number()
})

staff_channel.bind("create_sale",function(data) {
  $(function(){
    var notice = pop_notify({
      text: "Order mới từ " + data['sale']['customer']['email'],
    });

    append_order_init_row(data)
    set_notifications_number()
  });
});

staff_channel.bind("destroy_sale_menu_item",function(data) {
  $(function(){
    var notice = pop_notify({
      text: "Order từ " + data['sale_menu_item']['customer']['email'] + ' có thay đổi',
    });
    remove_sale_menu_item(data)
    set_notifications_number()
  });
});

staff_channel.bind("next_state_sale",function(data) {
  if(data['sale']['state'] == "pending") {
    $(function(){
      var notice = pop_notify({
        text: "Order " + data['sale']['id'] + " từ " + data['sale']['customer']['email'] + " đang được đi lấy tiền",
      });

      set_order_pending_row(data)

      user_id = "<%= current_user['id'] %>"
      if(user_id != data['sale']['pender_id']){
        sale_id = data['sale']['id']
        $(".order-row[sale-id="+sale_id+"]").remove()
        set_notifications_number()
        if($('.table-order-pending .order-row').length == 0)
        {
          $(".no-pending-orders").fadeIn(100)
        }
      }

    });
  }
  if(data['sale']['state'] == "processing") {
    sale_id = data['sale']['id']
    $(".order-row[sale-id="+sale_id+"]").remove()
    set_notifications_number()
  }
});

function remove_sale_menu_item(data){
  var sale_menu_item_id = data['sale_menu_item']['id'];
  var sale_id = data['sale_menu_item']['sale_id'];
  var price = parseFloat($('#tab-order-pending tbody tr#sale-'+ sale_id + ' .total-price .price').text().replace(/\,/g, ''));
  var sub_price = parseFloat(data['sale_menu_item']['quantity'])*parseFloat(data['sale_menu_item']['menu_item_details']['unit_price']);
  if ((price-sub_price) <= 0) {
    $('#tab-order-pending tbody tr#sale-'+ sale_id).remove();
  } else {
    $('#tab-order-pending tbody tr#sale-'+ sale_id + ' .total-price .price').text(number_format(price-sub_price));
  }
}

function append_order_init_row(data){
  sale_id = data['sale']['id']
  html = "<%=j render 'order_init_template' %>"
  $(".no-pending-orders").before(html)
  $(".order-init-template").attr("id", "sale-" + sale_id)
  $(".order-init-template").attr("sale-id", sale_id)
  $(".order-init-template .order-com").text(data['sale']['customer']['email'])

  $(".order-init-template .btn-go-to-payment").parent("li").addClass("active")

  $(".order-init-template").attr("data-target", "#order-action-dropdown-"+sale_id)

  $(".order-init-template").dropdown()

  $(".order-init-template .order-action button").attr("data-target", "#order-action-dropdown-"+sale_id)

  $(".order-init-template .order-action").attr("id", "order-action-dropdown-"+sale_id)

  $(".order-init-template .btn-go-to-payment").attr("href", "/waiter_pages/go_for_payment?sale_id="+sale_id)

  $(".order-init-template .total-price .price").text(number_format(data['sale']['total_price']))

  $(".order-init-template .order-created-at").html("Gọi lúc: " + data['sale']['format_created_at'])

  $(".order-init-template").removeClass("order-init-template")

  $(".order-row[sale-id="+sale_id+"]").click(function(){
    $(".order-row").removeClass("select-now")
    if($(this).hasClass("select-now"))
    {
      $(this).addClass("remove-now")
    }
    else{
      $(this).addClass("select-now")
    }
  })

  $(".order-row[sale-id="+sale_id+"] .btn-order-details").click(function(){
    $('.launch-modal').html("<%=j render 'waiter_pages/modal_sale_details' %>")
    $('#modal-sale-details').attr("sale-id", sale_id)
    $("#modal-sale-details").modal({
      keyboard: true,
      backdrop: 'static'
    })
  })

  $(".order-row[sale-id="+sale_id+"] .btn-go-to-payment").click(function(){
    $.ajax({
      type: "GET",
      url: $(this).attr('href')
    });
  })

  $(".order-row[sale-id="+sale_id+"] .btn-verify-payment").click(function(){
    $.ajax({
      type: "GET",
      url: $(this).attr('href')
    });
  })
}

function set_order_pending_row(data){
  sale_id = data['sale']['id']

  $(".order-row[sale-id="+sale_id+"] .btn-go-to-payment").parent("li").removeClass("active")

  $(".order-row[sale-id="+sale_id+"] .btn-go-to-payment").attr("href", "javascript:;")

  $(".order-row[sale-id="+sale_id+"] .btn-go-to-payment").removeAttr("data-remote")

  $(".order-row[sale-id="+sale_id+"] .btn-verify-payment").parent("li").addClass("active")

  $(".order-row[sale-id="+sale_id+"]").addClass("success")

  $(".order-row[sale-id="+sale_id+"] .btn-verify-payment").attr("href", "/waiter_pages/verify_payment?sale_id="+sale_id)

  $(".order-row[sale-id="+sale_id+"] .btn-verify-payment").attr("data-remote", "true" )

  $("#modal-sale-details").modal('hide')

  $(".modal-backdrop").remove()
}
</script>

app/views/waiter_pages/_sale_menu_item_template.html.erb
<tr data-toggle="dropdown" class='menu-item-row menu-item-template'>
  <td class='menu-item-name'>
    <div class="btn-group item-action pull-right" style="margin-top: 12px">
      <button type="button" style="padding-bottom: 2px;" class="btn btn-sm btn-primary dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
        <i class='fa fa-caret-down' style='font-size: 18px'></i>
      </button>
      <ul class="dropdown-menu">
        <li>
          <a class='btn-go-deliver' href='javascript:;'>Đi giao</a>
        </li>
        <li>
          <a class='btn-done-deliver' href='javascript:;'>Đã giao</a>
        </li>
        <li role="separator" class="divider"></li>
        <li class="active">
          <a class='btn-redo'>Làm lại</a>
        </li>
      </ul>
    </div>
    <div class='item-name'>
      
    </div>
    <small class='pull-left item-action-at' style='font-weight: normal; margin-top: 3px'>
    </small>
  </td>
</tr>

app/views/waiter_pages/sale_details.js.erb
$("#modal-sale-details .modal-body").html("<%=j render 'sale_details', sale: @sale['sale'] %>")
<% if @sale['sale']['state'] == 'init' %>
$(".modal-footer").prepend("<a data-remote='true' href='<%= go_for_payment_waiter_pages_path(sale_id: @sale['sale']['id']) %>' class='btn btn-primary pull-left'>Đi thu tiền</a>")
<% elsif @sale['sale']['state'] == "pending" %>
$(".modal-footer").prepend("<a data-remote='true' href='<%= verify_payment_waiter_pages_path(sale_id: @sale['sale']['id']) %>' class='btn btn-primary pull-left'>Đã thu tiền</a>")
<% end %>

app/views/waiter_pages/sale_list.html.erb
<script type="text/javascript">
var staff_channel = dispatcher.subscribe('staff');
var stack_context = {"dir1": "down", "dir2": "left", "push": "bottom", "spacing1": 5, "spacing2": 5}
</script>
<div class="waiter-pages">
  <div class="tabs-row">
    <div class="col-sm-4 col-lg-4 col-md-4 col-xs-4 no-padding">
      <div class="tab-list active" aria-control="tab-order-pending">
        THU <label class="badge badge-danger notify-order-pending notify-order"><%= @sales_pending.count %></label>
      </div>
    </div>
    <div class="col-sm-4 col-lg-4 col-md-4 col-xs-4 no-padding">
      <div class="tab-list" aria-control="tab-order-ready">
        GIAO <label class="badge badge-danger notify-order-ready notify-order"><%= @sales_ready.count %></label>
      </div>
    </div>
    <div class="col-sm-4 col-lg-4 col-md-4 col-xs-4 no-padding">
      <div class="tab-list" aria-control="tab-histories">
        LỊCH SỬ
      </div>
    </div>
  </div>
  <div class="tabs-content">
    <div class="col-xs-12 no-padding">
      <div class="tab-content" id="tab-order-pending">
        <%= render 'order_pending' %>
      </div>
      <div class="tab-content" id="tab-order-ready">
        <%= render 'order_ready' %>
      </div>
      <div class="tab-content" id="tab-histories">
        <%= render 'order_histories' %>
      </div>
      <br>
      <center>
        <a data-method="DELETE" href="/sessions">Đăng xuất</a>
      </center>
      <br>
    </div>
  </div>
</div>
<script>
$(document).ready(function () {
  set_notifications_number()

  <% if @histories %>
  $(".tab-list").removeClass("active")
  $(".tab-content").fadeOut(0)
  $("#tab-histories").fadeIn(300)
  $(".tab-list[aria-control=tab-histories]").addClass("active")
  <% end %>
});

$(".tab-list").click(function(){
  $(".tab-list").removeClass("active")
  $(this).addClass("active")
  tab_id = $(this).attr("aria-control")
  if(tab_id == "tab-histories"){
    if(window.confirm("Bạn có muốn tải lại trang này không? (Tải lại sẽ giúp bạn cập nhật được order mới giao)")){
      $(".table-order-histories tbody").html('<tr class="histories-loading"><td colspan="2"><center><i class="fa fa-spin fa-spinner" style="margin-right: 5px"></i> Đang tải dữ liệu</center></td></tr><tr class="no-histories-orders no-orders" style="display: none"><td colspan="3"><div class="alert alert-warning">Tạm thời không có order mới.</div></td></tr>')
      $.ajax({
        type: "GET",
        dataType: "script",
        url: "<%= delivered_sales_waiter_pages_path %>"
      });
    }
  }
  $(".tab-content").fadeOut(0)
  $("#"+tab_id).fadeIn(300)
})

function set_notifications_number(){
  notifications_pending_number = $(".table-order-pending .order-row").length

  notifications_ready_number = $(".table-order-ready .order-row.visible").length

  if(notifications_pending_number > 0)
  {
    $(".notify-order-pending").fadeIn(0)
    $(".no-pending-orders").fadeOut(0)
    $(".notify-order-pending").text(notifications_pending_number)
  }
  else{
    $(".notify-order-pending").fadeOut(0)
    $(".no-pending-orders").fadeIn(0)
  }

  if(notifications_ready_number > 0)
  {
    $(".notify-order-ready").fadeIn(0)
    $(".no-ready-orders").fadeOut(0)
    $(".notify-order-ready").text(notifications_ready_number)
  }
  else{
    $(".no-ready-orders").fadeIn(0)
    $(".notify-order-ready").fadeOut(0)
  }
}
</script>